version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres_1
    environment:
      POSTGRES_DB: recipes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ismoil_0709
    ports:
      - "5433:5432"  # Expose container's default port 5432 to host's port 5433
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_1
    ports:
      - "6379:6379"  # Use default Redis port

  app:
    build: .
    container_name: app-recipes
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_1:5432/recipes_db  # Match the updated application.yml
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ismoil_0709
      SPRING_REDIS_HOST: redis_1
    depends_on:
      - postgres
      - redis
    ports:
      - "80:80"

volumes:
  postgres-data:

