server:
  port: 80

spring:
  data:
    redis:
      port: 6379
      host: redis_1  # Use the service name defined in docker-compose.yml

  datasource:
    driver-class-name: org.postgresql.Driver
    password: ismoil_0709
    url: jdbc:postgresql://postgres_1:5432/recipes_db  # Use the service name here
    username: postgres

  mail:
    host: smtp.gmail.com
    port: 587
    username: abduganiyev.ismoil001@gmail.com
    password: lkeu ioml dypp zwed
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: never

  batch:
    jdbc:
      initialize-schema: always

app:
  token:
    expireDays: 3
    secretKey: '03d2430e18744da8db2b8dbd64a64977be5c1a7f06d52197c9b8113a3b552c69'
  code:
    attempt: 5

